"""initial_schema

Revision ID: bfe655e944b2
Revises: 
Create Date: 2026-09-16 19:01:31.128101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe655e944b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriority'), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_time_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sla_policies_id'), 'sla_policies', ['id'], unique=False)
    op.create_index(op.f('ix_sla_policies_priority'), 'sla_policies', ['priority'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('REQUESTER', 'OPERATOR', 'TEAM_LEAD', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('office_location', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key('fk_teams_lead_id', 'teams', 'users', ['lead_id'], ['id'], ondelete='SET NULL')

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriority'), nullable=False),
    sa.Column('default_team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('office_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'UNDERSTOOD', 'ASSIGNED', 'INVESTIGATING', 'ACTION_TAKEN', 'RESOLUTION_PROPOSED', 'CONFIRMED', 'CLOSED', 'WAITING_FOR_INFO', 'ESCALATED', 'DUPLICATE', 'REOPENED', 'CANCELLED', name='casestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriority'), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', 'CRITICAL', name='caseseverity'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_team_id', sa.Integer(), nullable=True),
    sa.Column('assigned_operator_id', sa.Integer(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('sla_breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_operator_id'), 'cases', ['assigned_operator_id'], unique=False)
    op.create_index(op.f('ix_cases_assigned_team_id'), 'cases', ['assigned_team_id'], unique=False)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_is_sla_breached'), 'cases', ['is_sla_breached'], unique=False)
    op.create_index(op.f('ix_cases_office_location'), 'cases', ['office_location'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_requester_id'), 'cases', ['requester_id'], unique=False)
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_title'), 'cases', ['title'], unique=False)
    op.create_table('ai_case_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True),
    sa.Column('suggested_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='casepriority'), nullable=True),
    sa.Column('suggested_severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', 'CRITICAL', name='caseseverity'), nullable=True),
    sa.Column('suggested_team_id', sa.Integer(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('recommended_questions', sa.JSON(), nullable=False),
    sa.Column('related_case_ids', sa.JSON(), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=True),
    sa.Column('case_summary', sa.Text(), nullable=True),
    sa.Column('risk_insight', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.String(length=50), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_case_analyses_case_id'), 'ai_case_analyses', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_case_analyses_id'), 'ai_case_analyses', ['id'], unique=False)
    op.create_table('case_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('escalated_by_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.Enum('REQUESTER', 'OPERATOR', 'TEAM_LEAD', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'CANCELLED', name='escalationstatus'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_escalations_case_id'), 'case_escalations', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_escalations_id'), 'case_escalations', ['id'], unique=False)
    op.create_index(op.f('ix_case_escalations_status'), 'case_escalations', ['status'], unique=False)
    op.create_table('case_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('COMMUNICATION', 'INFO_REQUEST', 'INFO_RESPONSE', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_messages_case_id'), 'case_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_messages_id'), 'case_messages', ['id'], unique=False)
    op.create_index(op.f('ix_case_messages_sender_id'), 'case_messages', ['sender_id'], unique=False)
    op.create_table('case_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('remaining_issues', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'REJECTED', name='resolutionstatus'), nullable=False),
    sa.Column('requester_feedback', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_resolutions_case_id'), 'case_resolutions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_resolutions_id'), 'case_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_case_resolutions_status'), 'case_resolutions', ['status'], unique=False)
    op.create_table('case_risk_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_risk_records_case_id'), 'case_risk_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_risk_records_id'), 'case_risk_records', ['id'], unique=False)
    op.create_index(op.f('ix_case_risk_records_risk_level'), 'case_risk_records', ['risk_level'], unique=False)
    op.create_table('case_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='taskstatus'), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_tasks_case_id'), 'case_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_tasks_id'), 'case_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_case_tasks_status'), 'case_tasks', ['status'], unique=False)
    op.create_table('in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('NEW_CASE', 'ASSIGNMENT', 'REQUESTER_RESPONSE', 'NEW_TASK', 'SLA_WARNING', 'ESCALATION', 'RESOLUTION', 'REOPENED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_case_id'), 'in_app_notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_created_at'), 'in_app_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_id'), 'in_app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_user_id'), 'in_app_notifications', ['user_id'], unique=False)
    op.create_table('internal_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_author_id'), 'internal_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_internal_notes_case_id'), 'internal_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_internal_notes_id'), 'internal_notes', ['id'], unique=False)
    op.create_table('investigation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_records_case_id'), 'investigation_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_records_id'), 'investigation_records', ['id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_created_at'), 'timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_table('case_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('is_resolution_evidence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['case_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_attachments_case_id'), 'case_attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_attachments_id'), 'case_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_attachments_id'), table_name='case_attachments')
    op.drop_index(op.f('ix_case_attachments_case_id'), table_name='case_attachments')
    op.drop_table('case_attachments')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_created_at'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_investigation_records_id'), table_name='investigation_records')
    op.drop_index(op.f('ix_investigation_records_case_id'), table_name='investigation_records')
    op.drop_table('investigation_records')
    op.drop_index(op.f('ix_internal_notes_id'), table_name='internal_notes')
    op.drop_index(op.f('ix_internal_notes_case_id'), table_name='internal_notes')
    op.drop_index(op.f('ix_internal_notes_author_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_index(op.f('ix_in_app_notifications_user_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_is_read'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_created_at'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_case_id'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    op.drop_index(op.f('ix_case_tasks_status'), table_name='case_tasks')
    op.drop_index(op.f('ix_case_tasks_id'), table_name='case_tasks')
    op.drop_index(op.f('ix_case_tasks_case_id'), table_name='case_tasks')
    op.drop_table('case_tasks')
    op.drop_index(op.f('ix_case_risk_records_risk_level'), table_name='case_risk_records')
    op.drop_index(op.f('ix_case_risk_records_id'), table_name='case_risk_records')
    op.drop_index(op.f('ix_case_risk_records_case_id'), table_name='case_risk_records')
    op.drop_table('case_risk_records')
    op.drop_index(op.f('ix_case_resolutions_status'), table_name='case_resolutions')
    op.drop_index(op.f('ix_case_resolutions_id'), table_name='case_resolutions')
    op.drop_index(op.f('ix_case_resolutions_case_id'), table_name='case_resolutions')
    op.drop_table('case_resolutions')
    op.drop_index(op.f('ix_case_messages_sender_id'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_id'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_case_id'), table_name='case_messages')
    op.drop_table('case_messages')
    op.drop_index(op.f('ix_case_escalations_status'), table_name='case_escalations')
    op.drop_index(op.f('ix_case_escalations_id'), table_name='case_escalations')
    op.drop_index(op.f('ix_case_escalations_case_id'), table_name='case_escalations')
    op.drop_table('case_escalations')
    op.drop_index(op.f('ix_ai_case_analyses_id'), table_name='ai_case_analyses')
    op.drop_index(op.f('ix_ai_case_analyses_case_id'), table_name='ai_case_analyses')
    op.drop_table('ai_case_analyses')
    op.drop_index(op.f('ix_cases_title'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.drop_index(op.f('ix_cases_requester_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_office_location'), table_name='cases')
    op.drop_index(op.f('ix_cases_is_sla_breached'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_team_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_operator_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_constraint('fk_teams_lead_id', 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sla_policies_priority'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_table('case_sequences')
    # ### end Alembic commands ###
