# Schemas package
from app.schemas.auth import (
    UserRegister,
    UserLogin,
    Token,
    TokenPayload,
    UserResponse,
    UserUpdate,
)
from app.schemas.case import (
    UserSimple,
    TeamSimple,
    CategorySimple,
    CaseCreate,
    CaseUpdate,
    CaseStatusUpdate,
    CaseAssign,
    CaseResponse,
    CaseListResponse,
    TimelineEventResponse,
)

from app.schemas.ai import (
    AICaseAnalysisResponse,
    AICaseAnalysisReviewRequest,
    AIDraftMessageRequest,
    AIDraftMessageResponse,
    AIDuplicateCheckRequest,
    AIDuplicateCheckResponse,
    AIDuplicateMatch,
)

from app.schemas.sla import (
    SLAPolicyResponse,
    SLAPolicyCreate,
    SLAPolicyUpdate,
    CaseSLAStatusResponse,
    CaseRiskRecordResponse,
    CaseRiskEvaluationResponse,
    CaseEscalationCreate,
    CaseEscalationResponse,
    CaseEscalationResolveRequest,
    SLASweepSummaryResponse,
)

__all__ = [
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenPayload",
    "UserResponse",
    "UserUpdate",
    "UserSimple",
    "TeamSimple",
    "CategorySimple",
    "CaseCreate",
    "CaseUpdate",
    "CaseStatusUpdate",
    "CaseAssign",
    "CaseResponse",
    "CaseListResponse",
    "TimelineEventResponse",
    "AICaseAnalysisResponse",
    "AICaseAnalysisReviewRequest",
    "AIDraftMessageRequest",
    "AIDraftMessageResponse",
    "AIDuplicateCheckRequest",
    "AIDuplicateCheckResponse",
    "AIDuplicateMatch",
    "SLAPolicyResponse",
    "SLAPolicyCreate",
    "SLAPolicyUpdate",
    "CaseSLAStatusResponse",
    "CaseRiskRecordResponse",
    "CaseRiskEvaluationResponse",
    "CaseEscalationCreate",
    "CaseEscalationResponse",
    "CaseEscalationResolveRequest",
    "SLASweepSummaryResponse",
]
